# Stage 1: Build
FROM node:18-alpine AS builder
ENV PNPM_HOME="/pnpm"
#tells pnpm to install here
ENV PATH="$PNPM_HOME:$PATH"
#marks this path for pnpm package installations
ENV CI=true
#tells that it is in continous intrigation environment
RUN corepack enable
#manage packages npm, yarn, pnpm
WORKDIR /app

# Copy essential files first
COPY frontend/package.json frontend/pnpm-lock.yaml frontend/.env ./

# Install dependencies and build
RUN pnpm install --frozen-lockfile
#Don't modify the lockfile during installation
COPY frontend/ ./
RUN pnpm build

# Stage 2: Runtime
FROM node:18-alpine
WORKDIR /app

# Copy only necessary production files
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.next/server ./.next/server
COPY --from=builder /app/public ./public
COPY --from=builder /app/.env ./

EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]