# Generated by Django 5.2.1 on 2025-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_projects',
            field=models.IntegerField(default=0),
        ),
    ]
