# Generated by Django 4.2.21 on 2025-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc_api', '0002_organization_rating_organization_total_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
